### PR TITLE
Merge upstream/4.0-dev into brianteeman/messages

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for [https://github.com/joomla/joomla-cms/pull/27096](https://github.com/joomla/joomla-cms/pull/27096).

### Summary of Changes

This PR is the complete merge of the 4.0-dev base branch into your `messages` branch.

To verify if this PR is correct, compare the branch of this PR (= **my** `messages` branch) with the 4.0-dev branch of the CMS. It should show only the changes from your PR (if no update in the 4.0-dev branch since I wrote this, but if so, ping me, and I update my branch to base so it is again like I said), except of the `lft` and `rgt` values in the menus table, see ATTENTION section below.

If you don't want to merge this PR because you want to do it differently, or if GitHub shows that it can't be merged due to conflicts, then update your `messages` branch to the base branch yourself and just pick the two `joomla.sql` files from this PR here and mark the conflicts as resolved, and then ping me when I shall close this PR.

**ATTENTION:** The `lft` and `rgt` values in the menus table are not corrected yet, this PR just solves the merge conflict. But `parent_ids` values are set correctly. Do you use a tool to calculate `lft` and `rgt` (Nicola uses a tool normally)? Or do you do it manually? And could you do that yourself, or shall I help with that too? Let me know if I should help, then we can correct this PR here, or you just pick the two `joomla.sql` files into your PR and then we correct the `lft` and `rgt` values after that in your PR.

### CODE REVIEW

**Comment by brianteeman** [comment]
This branch cannot be rebased due to conflicts

**Comment by richard67** [comment]
How do you normally update your branches to 4.0-dev? Do you use the button on GH, or do you do it locally on your clone on your PC or laptop?

**Comment by richard67** [comment]
P.S. Is not a real rebase we need  to do. Is just a "merge upstream/4.0-dev into your messages branch" we have to do. After that your tool will show you that there are conflicts in the 2 joomla.sql files. Then you just pick those 2 files from this PR, then you tell your tool that conflicts are resolved and commit my 2 files. If you use GitHub Desktop I can advise more detailled.

**Comment by brianteeman** [comment]
Weird
 Mobile says it can be merged

**Comment by richard67** [comment]
Of course we can chat here too for advise and so on, so no need for glip. Only in your CMS PR I don't wanna discuss too much, in order not to blow it up.

**Comment by richard67** [comment]
after that we have to fix lft and rgt

**Comment by richard67** [comment]
On desktop here GitHub sais it can be merged when i compare my branch of this PR with your messages branch, and it also sais it can be merged when i compary my branch with 4.0-dev of the cms, so i think you can just merge this one. But if you wanna be safe, do it in the careful way: merge upstream/4.0-dev into your branch locally, then use my joomla.sql files.

**Comment by brianteeman** [comment]
wait I jjust realised that its the restyled tool i have running

**Comment by brianteeman** [comment]
can you just push a small change so that it can be rechecked and the now removed tool will stop preventing the merge

**Comment by richard67** [comment]
Done.

**Comment by brianteeman** [comment]
didnt - work - it still thinks there are issues - I will do it manually.

**Comment by richard67** [comment]
Ok, am available for a while. Let me know when questions or done. Don't forget, lft and rgt need to be fixed after that. You can do that, or shall we ask Nicola or whomever else?

**Comment by brianteeman** [comment]
merged

**Comment by richard67** [comment]
Great. Don't forget lft and rgt ;-) (in ceterum censio ... )

**Pull request merged**
