### PR TITLE
Fix multiselect, clean a table name, prevent incorrect index

### PR DESCRIPTION
**Pull request by Fedik**
That should fix checkboxes bug, and some additional fixes

### CODE REVIEW

**Comment by brianteeman** [comment]
merging to test

**Comment by brianteeman** [comment]
This resolves the issue about not being able to select items etc but it loses the ability to click on a row to select it which you fixed before

**Comment by brianteeman** [comment]
correction

this breaks everything - checking a row also checks an item in the column select

**Comment by Fedik** [comment]
Are you sure?
I tested it locally, I was able to check the row etc.

**Comment by brianteeman** [comment]
going to do a complete reset and test again

**Comment by brianteeman** [comment]
Dont know what happened but it works now

**Pull request merged**
