### PR TITLE
Correct schema updates for pr 26047

### PR DESCRIPTION
**Pull request by richard67**
See [https://github.com/joomla/joomla-cms/pull/26047#issuecomment-525376631](https://github.com/joomla/joomla-cms/pull/26047#issuecomment-525376631).

### CODE REVIEW

**Comment by brianteeman** [comment]
this is completely wrong - you never change user data. This is not a schema update

**Comment by richard67** [comment]
Then tell it those who have created that schema update, that was not me. I only say as long as we can change it, i.e. before beta, we should change it so it is consistent with joomla.sql. Anyway I will close discussion.

**Comment by brianteeman** [comment]
The database schema of a database system is its structure described in a formal language supported by the database management system. The term "schema" refers to the organization of data as a blueprint of how the database is constructed

nothing to do with content

**Comment by richard67** [comment]
Then call it update sql abused for content updates. All I said is change it as long as we can. And there is no need to explain me what a schema is.

**Pull request closed without merging**
