### PR TITLE
user js

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
please test

### CODE REVIEW

**Comment by brianteeman** [comment]
Thanks. I will merge and test tomorrow. Was a little busy tonight for
obvious reasons

**Comment by andrepereiradasilva** [comment]
of course

**Comment by brianteeman** [comment]
@andrepereiradasilva I merged it and  it almost works

1. you were correct no need to check if the file exists
2. protostar all good
3. beez3 doesnt work - I am guessing thats because beez3 uses a /javascript/ and not /js/

**Comment by andrepereiradasilva** [comment]
> beez3 doesnt work - I am guessing thats because beez3 uses a /javascript/ and not /js/ 

"javascript" ahhh?? ....

**Comment by andrepereiradasilva** [comment]
ok will check

**Comment by andrepereiradasilva** [comment]
see https://github.com/brianteeman/joomla-cms/pull/14

**Pull request merged**
