### PR TITLE
Translate Suffix

### PR DESCRIPTION
**Pull request by Bakual**
I didn't test it, but from my theory it should work. Just to explain what I mean.

### CODE REVIEW

**Comment by brianteeman** [comment]
Thanks I will test it

My comment about it being too complex was not about for the developer writing the code but the user trying to implement it

**Comment by Bakual** [comment]
Yeah, for the user it will be complex to use. But I guess only those who already understand how it works will ever want to use this feature anyway.
One more for your "Hidden Secrets" series 😄

**Comment by brianteeman** [comment]
I am assuming that the idea of this code and the code above for the label is that if the user enters a language constant then the related language value would be displayed?

If so then it doesn't work i either case. 

image

**Comment by Bakual** [comment]
It only works if the respective language file is loaded where the constant is defined. Since the constant you used are from backend and you try it in frontend it will not work. Those constants aren't loaded and thus can't be found.
I tested the label with strings I added in the language manager -> override and that one worked.
I have some spare time now at work - I'll try my PR now :)

**Comment by Bakual** [comment]
Works here:
image

image

**Comment by Bakual** [comment]
My example in your PR was wrong of course. There doesn't need to be an _N which is replaced. Just the suffixes are important, the naming of the constant itself doesn't matter at all.

**Comment by brianteeman** [comment]
ok worked it out

**Pull request closed without merging**
