### PR TITLE
Brian a11y

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for Issue https://github.com/joomla/joomla-cms/pull/15046

### Summary of Changes

drone

### CODE REVIEW

**Comment by brianteeman** [comment]
Doesn't look right.

**Comment by zero-24** [comment]
why?

**Comment by brianteeman** [comment]
My reading of the test failures means the tests need updating not the code. Ofc i could be completely wrong

**Comment by zero-24** [comment]
Drone complains about to long lines. The unittests (travis) is not fixed here. I need to check that as the result of travis (unittest) looks strange to me.

**Comment by brianteeman** [comment]
I only looked at Travis - hence the confusion :)

**Comment by brianteeman** [comment]
merging these and then hopefully someone else can help wth the travis erros

**Comment by zero-24** [comment]
done here: https://github.com/brianteeman/joomla-cms/pull/9

**Pull request merged**
