### PR TITLE
Move logic to model

### PR DESCRIPTION
**Pull request by HLeithner**
Also added a more future proved way to add information to the layout.

### CODE REVIEW

**Comment by HLeithner** [comment]
I'm still fixing some things

**Comment by brianteeman** [comment]
ok - ping back when its ready. 

Now you can see the limits of my abilities ;)

**Comment by HLeithner** [comment]
So this part is ready, wanted to make it possible to layout this in the template but then the "htmlhelper link" comes between me and the solution... and I didn't want to make it to complicated

**Comment by brianteeman** [comment]
yeah I tried the layout route myself and failed ;)

**Comment by HLeithner** [comment]
js still missing, no idea if we have already a solution for this somewhere in our code base. I know it only from the menu button to call some js for reloading...

**Comment by brianteeman** [comment]
yes we have the js for it in admin-add_module.js

it is used to refresh the cpanel after adding a module

**Comment by brianteeman** [comment]
Could you explain this code
`				<?php echo Text::sprintf(...$message['message']); ?>
`
Also does it really need to be an array of messages as you will only ever have one?

**Comment by HLeithner** [comment]
Thats the future proof part ;). I want to have this as patten also for other libs and extensions.

My first approach was to have an additional key containing the parts to build the link in the template, but ended with the feeling of over engineering...

...$array explodes the array to function parameters...

Maybe it makes sense to move the foreach part to a layout then we could move the link creation there too

**Comment by brianteeman** [comment]
I understand you now about the new code. 

If you can document that a bit then I can have a go at converting others.

**Comment by HLeithner** [comment]
No sure if I can do this today, no lunch and then I have to assemble my new pc...

I will came up with a better solution later or tomorrow

**Comment by brianteeman** [comment]
no problem. I am doing something similar now for smart-search but its much easier for that component

**Pull request merged**
