### PR TITLE
Add rtlcss in the mix

### PR DESCRIPTION
**Pull request by dgrammatiko**
Requires an entry point in the templates ending with `-rtl.scss`, eg `template-rtl.scss`

Pull Request for Issue # .

### CODE REVIEW

**Comment by brianteeman** [comment]
why does it need the -rtl.scss enytry point?

the whole point of rtlcss is that it works from the template.CSS

**Comment by dgrammatiko** [comment]
> why does it need the -rtl.scss enytry point?

It's basically how the build tools work, they need an entry point to create the .css and .min.css. Adding the entry point (it's just a copy of the same template.scss, so it hardly will ever be touched) means that the tools will work for any template, not just atum or cassiopeia. The other way is to hardcode the `template.scss` to run twice and produce the `-rtl` files but that will work only for the hardcoded files. The tools are working on the folder/filename conventions, they can not apply arbitrary logic with out some input...


Actually the template-rtl.scss needs only one line


```scss
// Just import the template.scss
@import "template";
```

**Comment by brianteeman** [comment]
one of us is missing something - in my non-technical terms the workflow would be

1. generate template.css into the media folder
2. run rtlcss on media/template.css to create media/template-rtl.css 
3. minify both files

**Comment by brianteeman** [comment]
update - just saw the import one line idea.
I guess that will work as well

will test in the morning

**Comment by brianteeman** [comment]
Unfortunatley that doesnt work

IT seems to get as far as creating the css folders and then dies 

image

**Comment by dgrammatiko** [comment]
@brianteeman check https://github.com/brianteeman/joomla-cms/pull/292

I used the code from v5 which has quite some changes in the first PR

**Pull request merged**
